### ISSUE TITLE
flatpak build is behind official version

### ISSUE THREAD

**Issue by dafzor** [flathub/net.rpcs3.RPCS3#1761]
Latest official build is  Build 0.0.34-17151  but flatpak version is still  0.0.33-1-3e516df2 Alpha

**Comment by j8r** [comment]
The build is done once per week to avoid overloading Flathub build servers, they asked us to do it.
We may want to enable automerge, which has been denied by default since https://github.com/flathub-infra/flatpak-builder-lint/pull/426

**Comment by bbhtt** [comment]
Most of your official builds are failing because the commit from the master branch is being moved to a different SHA by the time you merge. This is the problem the branch check was supposed to prevent.

**Comment by bbhtt** [comment]
I added an automerge exception for this, on the condition of this being updated weekly. Please don't increase the frequency.

**Comment by j8r** [comment]
Thanks!

**Comment by duhow** [comment]
@bbhtt @j8r we still don't have any update available from Flathub, can you help check? 🙏🏻

**Comment by j8r** [comment]
I have to add the automerge option to https://github.com/flathub/net.rpcs3.RPCS3/blob/master/flathub.json, I'll do that in a week.

**Comment by j8r** [comment]
@bbhtt I notice now there is an automerge feature natively in GitHub, can we enable that?
It will be more robust to waht we have currently (running twice the flatpak checker).

**Comment by bbhtt** [comment]
Automerge is already enabled here, but you need to set the PRs to auto-merge. It won't merge automatically on its own with that enabled. 

It needs a step like

```yaml
      - name: Set auto-merge
        run: gh pr merge --rebase --auto $PR_NUMBER
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
```
